# -*- coding: utf-8 -*-
"""
/***************************************************************************
AgisAnaliza
                                 A QGIS plugin
 Zbirka orodij za arheologe analitike
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-02-14
        copyright            : (C) 2020 by Matjaž Mori
        email                : matjaz.mori@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AgisAnaliza class from file AgisAnaliza.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    from .agis_analiza import AgisAnaliza
    return AgisAnaliza()
